### ISSUE TITLE
Is there a .NET Framework based version available?

### ISSUE THREAD

**Issue by softempire** [aardvark-community/CeresSharp#1]
Thanks for implementing the library! I want to use it in a .NET Framework 4.6.1 based the product, is there a corresponding CeresSharp available?

**Comment by aszabo314** [comment]
Hi! This library is target platform netstandard2.0 and can be referenced from .net Framework 4.6.1 projects. I just successfully tried it using Visual Studio 2019.  My test code:

```fsharp
    Aardvark.Base.Aardvark.Init() //don't forget

    use p = new Problem()
    let bl = p.AddParameterBlock [|0.0|]
    p.AddCostFunction(1,bl,(fun v i -> 
        let a = Aardvark.Base.scalar 15.0 
        let b = v.[0]
        a+b
    ))
    let s = p.Solve(Config.empty)
```

**Comment by softempire** [comment]
Thank you!
